# Generated by Django 5.0.4 on 2025-01-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Support', 'Support'), ('Offer', 'Special offer'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='contact_files/')),
                ('consent', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='siteedit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(blank=True, default=models.CharField(blank=True, max_length=50, null=True), max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('dis', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('idx', models.IntegerField(default=1)),
                ('facebooklink', models.CharField(blank=True, max_length=500, null=True)),
                ('twiiterlink', models.CharField(blank=True, max_length=500, null=True)),
                ('instergram', models.CharField(blank=True, max_length=500, null=True)),
                ('youtubelink', models.CharField(blank=True, max_length=500, null=True)),
                ('whatsapplonk', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
