# Generated by Django 5.0.4 on 2025-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='owneremail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
