# Generated by Django 5.0.4 on 2025-01-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_siteedit_owneremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='files',
            field=models.URLField(blank=True, null=True),
        ),
    ]
