# Generated by Django 5.0.4 on 2025-01-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contactmessage_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
