# Generated by Django 5.0.4 on 2025-01-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contactmessage_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteedit',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
