# Generated by Django 5.0.4 on 2025-01-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_siteedit_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteedit',
            old_name='domain',
            new_name='host',
        ),
    ]
