# Generated by Django 5.0.4 on 2025-01-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_domain_siteedit_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteedit',
            old_name='host',
            new_name='domain',
        ),
    ]
